import { ComponentStory, ComponentMeta } from "@storybook/react";
import ProductTemplate from "./ProductTemplate";

export default {
  title: "templates/Product Template",
  component: ProductTemplate,
} as ComponentMeta<typeof ProductTemplate>;

const Template: ComponentStory<typeof ProductTemplate> = (args) => (
  <ProductTemplate {...args} />
);
export const Product = Template.bind({});
Product.args = {
  meta: {
    totalItems: 100,
    itemCount: 100,
    itemsPerPage: 500,
    totalPages: 1,
    currentPage: 1,
  },
  links: {
    first: "https://join-tsh-api-staging.herokuapp.com/products?limit=500",
    previous: "",
    next: "",
    last: "https://join-tsh-api-staging.herokuapp.com/products?page=1&limit=500",
  },
  items: [
    {
      id: 1,
      name: "Incredible Plastic Pizza",
      description: "Molestiae iure eum voluptas culpa et ut quasi.",
      rating: 2,
      image: "https://picsum.photos/640/480?random=1074",
      promo: true,
      active: true,
    },
    {
      id: 2,
      name: "Licensed Cotton Soap",
      description: "Commodi repellat illo facilis.",
      rating: 2,
      image: "https://picsum.photos/640/480?random=5623",
      promo: true,
      active: false,
    },
    {
      id: 3,
      name: "Tasty Rubber Car",
      description:
        "Explicabo accusamus optio facilis nobis officiis sed nisi omnis quia.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=2281",
      promo: true,
      active: true,
    },
    {
      id: 4,
      name: "Generic Metal Shirt",
      description:
        "Molestias atque repudiandae hic consequuntur voluptatem repellat magni.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=1573",
      promo: false,
      active: false,
    },
    {
      id: 5,
      name: "Fantastic Fresh Ball",
      description:
        "Aliquam delectus sapiente est cumque odio veniam reiciendis voluptatem distinctio.",
      rating: 1,
      image: "https://picsum.photos/640/480?random=5147",
      promo: true,
      active: true,
    },
    {
      id: 6,
      name: "Awesome Fresh Gloves",
      description: "Ut dicta et minima.",
      rating: 1,
      image: "https://picsum.photos/640/480?random=7135",
      promo: true,
      active: false,
    },
    {
      id: 7,
      name: "Unbranded Concrete Sausages",
      description: "Voluptatibus maxime odit fugit quo qui maxime.",
      rating: 1,
      image: "https://picsum.photos/640/480?random=2664",
      promo: true,
      active: false,
    },
    {
      id: 8,
      name: "Small Wooden Gloves",
      description: "At facere non nisi autem.",
      rating: 1,
      image: "https://picsum.photos/640/480?random=3559",
      promo: false,
      active: true,
    },
    {
      id: 9,
      name: "Practical Concrete Mouse",
      description: "Nulla dolor et at cumque perferendis dignissimos omnis.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=3772",
      promo: false,
      active: true,
    },
    {
      id: 10,
      name: "Licensed Plastic Bike",
      description: "Delectus asperiores debitis culpa.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=8090",
      promo: false,
      active: false,
    },
    {
      id: 11,
      name: "Unbranded Fresh Salad",
      description: "Aut nihil nemo rerum et.",
      rating: 1,
      image: "https://picsum.photos/640/480?random=7237",
      promo: false,
      active: true,
    },
    {
      id: 12,
      name: "Refined Metal Fish",
      description: "Voluptas atque sit aut ea ea.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=1251",
      promo: true,
      active: false,
    },
    {
      id: 13,
      name: "Ergonomic Frozen Car",
      description: "Nihil quam dolores eos.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=7252",
      promo: true,
      active: false,
    },
    {
      id: 14,
      name: "Refined Rubber Table",
      description:
        "Sed ratione vero magnam perferendis eum officiis perferendis ipsum.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=8198",
      promo: false,
      active: true,
    },
    {
      id: 15,
      name: "Refined Frozen Chair",
      description: "Expedita quisquam molestias.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=7363",
      promo: true,
      active: true,
    },
    {
      id: 16,
      name: "Sleek Rubber Table",
      description: "Eveniet ipsam eum laudantium unde hic nostrum.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=3785",
      promo: true,
      active: true,
    },
    {
      id: 17,
      name: "Refined Fresh Gloves",
      description: "Atque commodi qui aut velit est aut quae voluptas.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=355",
      promo: true,
      active: true,
    },
    {
      id: 18,
      name: "Practical Cotton Computer",
      description: "Quo molestiae aut aut et quos veniam.",
      rating: 2,
      image: "https://picsum.photos/640/480?random=3919",
      promo: false,
      active: false,
    },
    {
      id: 19,
      name: "Sleek Plastic Computer",
      description: "Porro et sunt laudantium animi.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=7153",
      promo: true,
      active: true,
    },
    {
      id: 20,
      name: "Handcrafted Granite Tuna",
      description: "Nam eum praesentium eius animi aliquam.",
      rating: 1,
      image: "https://picsum.photos/640/480?random=4533",
      promo: true,
      active: false,
    },
    {
      id: 21,
      name: "Refined Wooden Shirt",
      description: "Aut saepe et.",
      rating: 2,
      image: "https://picsum.photos/640/480?random=2056",
      promo: true,
      active: false,
    },
    {
      id: 22,
      name: "Practical Wooden Chips",
      description: "Ab molestiae id sint aut maiores qui aut vel saepe.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=1764",
      promo: false,
      active: false,
    },
    {
      id: 23,
      name: "Generic Steel Towels",
      description: "Itaque similique et eos.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=8825",
      promo: false,
      active: true,
    },
    {
      id: 24,
      name: "Handmade Granite Pizza",
      description: "Voluptas iste ad corporis quidem autem.",
      rating: 2,
      image: "https://picsum.photos/640/480?random=6134",
      promo: true,
      active: true,
    },
    {
      id: 25,
      name: "Handmade Plastic Sausages",
      description:
        "Exercitationem nisi sit exercitationem accusamus ab accusantium.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=7102",
      promo: true,
      active: false,
    },
    {
      id: 26,
      name: "Ergonomic Fresh Sausages",
      description:
        "Fuga voluptates molestiae accusamus ea accusantium eos necessitatibus.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=6112",
      promo: true,
      active: false,
    },
    {
      id: 27,
      name: "Generic Soft Chicken",
      description: "Ea consequatur sit cupiditate nisi.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=61",
      promo: false,
      active: true,
    },
    {
      id: 28,
      name: "Practical Fresh Shoes",
      description: "Nostrum facilis odit est ut itaque esse eius voluptas in.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=8154",
      promo: false,
      active: true,
    },
    {
      id: 29,
      name: "Gorgeous Frozen Fish",
      description: "Culpa itaque et dolor consequatur corrupti.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=3420",
      promo: false,
      active: true,
    },
    {
      id: 30,
      name: "Tasty Wooden Mouse",
      description: "Ex omnis ut optio ipsam eveniet.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=3618",
      promo: true,
      active: false,
    },
    {
      id: 31,
      name: "Rustic Plastic Pants",
      description: "Inventore odit aut hic rerum rerum quia sed voluptas.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=3873",
      promo: true,
      active: true,
    },
    {
      id: 32,
      name: "Fantastic Concrete Soap",
      description: "Fuga facere voluptates consequatur eius eveniet illo.",
      rating: 1,
      image: "https://picsum.photos/640/480?random=2486",
      promo: false,
      active: true,
    },
    {
      id: 33,
      name: "Generic Fresh Shirt",
      description: "Consequatur saepe aliquid et in.",
      rating: 2,
      image: "https://picsum.photos/640/480?random=8892",
      promo: false,
      active: true,
    },
    {
      id: 34,
      name: "Sleek Fresh Bacon",
      description: "Minima et culpa illum itaque et beatae quia quo.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=7477",
      promo: false,
      active: false,
    },
    {
      id: 35,
      name: "Unbranded Frozen Hat",
      description:
        "Blanditiis rerum exercitationem dicta minima vitae tempore qui vel tenetur.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=5576",
      promo: false,
      active: false,
    },
    {
      id: 36,
      name: "Handcrafted Cotton Mouse",
      description: "Nulla voluptates beatae eius accusantium iusto quod.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=8394",
      promo: false,
      active: true,
    },
    {
      id: 37,
      name: "Refined Steel Cheese",
      description: "Temporibus ut est odit omnis necessitatibus ratione quod.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=182",
      promo: false,
      active: true,
    },
    {
      id: 38,
      name: "Refined Concrete Gloves",
      description: "Ut iure nulla cum rerum earum quae dolorem laborum.",
      rating: 2,
      image: "https://picsum.photos/640/480?random=76",
      promo: true,
      active: true,
    },
    {
      id: 39,
      name: "Ergonomic Fresh Shirt",
      description: "Ipsa autem accusamus.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=2003",
      promo: true,
      active: true,
    },
    {
      id: 40,
      name: "Licensed Cotton Bacon",
      description: "Facilis autem quia et itaque.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=2853",
      promo: true,
      active: true,
    },
    {
      id: 41,
      name: "Rustic Soft Chicken",
      description: "Voluptatem magni sit voluptatem beatae aliquid.",
      rating: 1,
      image: "https://picsum.photos/640/480?random=781",
      promo: false,
      active: false,
    },
    {
      id: 42,
      name: "Sleek Plastic Bike",
      description: "Id occaecati tempora facilis id modi.",
      rating: 2,
      image: "https://picsum.photos/640/480?random=6831",
      promo: true,
      active: false,
    },
    {
      id: 43,
      name: "Incredible Steel Bacon",
      description: "Cumque hic possimus fugit velit.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=3368",
      promo: true,
      active: false,
    },
    {
      id: 44,
      name: "Practical Frozen Chips",
      description:
        "Odit exercitationem voluptatibus nisi asperiores eos qui id et.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=3006",
      promo: false,
      active: false,
    },
    {
      id: 45,
      name: "Practical Plastic Hat",
      description:
        "Rerum debitis beatae enim assumenda corporis et amet earum quis.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=3747",
      promo: true,
      active: false,
    },
    {
      id: 46,
      name: "Refined Soft Salad",
      description:
        "Esse suscipit quo hic quia et incidunt laboriosam nostrum nulla.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=2169",
      promo: false,
      active: false,
    },
    {
      id: 47,
      name: "Handcrafted Concrete Car",
      description: "Ut aspernatur qui et id.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=7438",
      promo: true,
      active: true,
    },
    {
      id: 48,
      name: "Ergonomic Steel Shoes",
      description: "Aliquid nihil dignissimos qui qui blanditiis.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=3851",
      promo: false,
      active: true,
    },
    {
      id: 49,
      name: "Awesome Plastic Chicken",
      description: "In nihil enim debitis qui.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=7339",
      promo: false,
      active: true,
    },
    {
      id: 50,
      name: "Fantastic Soft Mouse",
      description:
        "Ea itaque alias non qui quia veniam tempore suscipit voluptate.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=9409",
      promo: false,
      active: true,
    },
    {
      id: 51,
      name: "Gorgeous Frozen Soap",
      description: "Beatae nihil commodi hic voluptate.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=2302",
      promo: false,
      active: false,
    },
    {
      id: 52,
      name: "Awesome Granite Chips",
      description: "In voluptate esse vero.",
      rating: 2,
      image: "https://picsum.photos/640/480?random=7506",
      promo: true,
      active: true,
    },
    {
      id: 53,
      name: "Generic Wooden Hat",
      description: "Eos non dolorem sapiente quas rerum.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=7405",
      promo: false,
      active: false,
    },
    {
      id: 54,
      name: "Rustic Rubber Towels",
      description:
        "Voluptatem expedita voluptatem quia quam laudantium perspiciatis asperiores veniam.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=4439",
      promo: false,
      active: false,
    },
    {
      id: 55,
      name: "Sleek Cotton Keyboard",
      description: "Qui voluptas placeat aut id.",
      rating: 2,
      image: "https://picsum.photos/640/480?random=9769",
      promo: false,
      active: false,
    },
    {
      id: 56,
      name: "Tasty Rubber Fish",
      description: "Rerum omnis fugiat rem est earum sit enim aut harum.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=2920",
      promo: false,
      active: false,
    },
    {
      id: 57,
      name: "Fantastic Rubber Sausages",
      description: "Quas ullam enim a quia expedita.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=8236",
      promo: false,
      active: true,
    },
    {
      id: 58,
      name: "Small Wooden Tuna",
      description: "Reprehenderit labore facilis architecto.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=6512",
      promo: true,
      active: true,
    },
    {
      id: 59,
      name: "Licensed Wooden Mouse",
      description: "Ut voluptatem aut cupiditate dolorum.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=5026",
      promo: true,
      active: false,
    },
    {
      id: 60,
      name: "Small Frozen Sausages",
      description: "Nihil dignissimos omnis assumenda.",
      rating: 1,
      image: "https://picsum.photos/640/480?random=1039",
      promo: false,
      active: true,
    },
    {
      id: 61,
      name: "Incredible Metal Computer",
      description: "Ut officiis blanditiis et ut deserunt.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=3611",
      promo: true,
      active: true,
    },
    {
      id: 62,
      name: "Tasty Soft Salad",
      description:
        "Debitis eveniet ut distinctio dignissimos et unde sint maiores.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=5967",
      promo: true,
      active: true,
    },
    {
      id: 63,
      name: "Sleek Granite Bacon",
      description:
        "Inventore porro quia doloribus vel odit odio reprehenderit aliquid ut.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=8337",
      promo: false,
      active: false,
    },
    {
      id: 64,
      name: "Intelligent Plastic Shirt",
      description: "Non delectus omnis vel aliquam.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=3083",
      promo: false,
      active: false,
    },
    {
      id: 65,
      name: "Refined Wooden Keyboard",
      description:
        "Assumenda et accusantium facilis et rem blanditiis officiis.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=5239",
      promo: false,
      active: false,
    },
    {
      id: 66,
      name: "Generic Concrete Chips",
      description: "Illo harum rerum deserunt.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=397",
      promo: false,
      active: false,
    },
    {
      id: 67,
      name: "Small Rubber Bike",
      description: "Ratione voluptatem minima et maiores.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=2148",
      promo: true,
      active: false,
    },
    {
      id: 68,
      name: "Practical Concrete Pizza",
      description: "Eveniet ea et asperiores.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=2225",
      promo: true,
      active: true,
    },
    {
      id: 69,
      name: "Tasty Frozen Towels",
      description: "Quasi aut iste incidunt similique natus praesentium.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=9359",
      promo: false,
      active: false,
    },
    {
      id: 70,
      name: "Small Wooden Ball",
      description:
        "Eveniet dolor aut enim alias nesciunt sit vel voluptatibus.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=2467",
      promo: true,
      active: false,
    },
    {
      id: 71,
      name: "Sleek Wooden Chicken",
      description: "Qui architecto omnis temporibus et odit amet rerum.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=4174",
      promo: true,
      active: true,
    },
    {
      id: 72,
      name: "Intelligent Plastic Soap",
      description: "Minima nobis quia dolorem.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=5013",
      promo: false,
      active: false,
    },
    {
      id: 73,
      name: "Intelligent Cotton Bike",
      description: "Tempore ullam repellat placeat quis similique vel et.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=6658",
      promo: true,
      active: false,
    },
    {
      id: 74,
      name: "Gorgeous Cotton Chicken",
      description:
        "Nostrum eos quidem inventore non vitae ut debitis animi iste.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=4282",
      promo: true,
      active: true,
    },
    {
      id: 75,
      name: "Unbranded Steel Chicken",
      description:
        "Ut fuga qui natus consequatur sit nobis culpa debitis ipsum.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=8386",
      promo: false,
      active: true,
    },
    {
      id: 76,
      name: "Sleek Rubber Tuna",
      description:
        "Sed consequuntur debitis ea quas sunt soluta a consequatur.",
      rating: 1,
      image: "https://picsum.photos/640/480?random=1555",
      promo: true,
      active: false,
    },
    {
      id: 77,
      name: "Intelligent Granite Keyboard",
      description: "Et nobis quidem eveniet id ducimus et eos.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=5446",
      promo: true,
      active: false,
    },
    {
      id: 78,
      name: "Generic Rubber Computer",
      description:
        "Perspiciatis excepturi iusto aut architecto et culpa deserunt.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=9083",
      promo: false,
      active: true,
    },
    {
      id: 79,
      name: "Small Metal Chicken",
      description: "Et consequatur vel voluptates sit sint.",
      rating: 2,
      image: "https://picsum.photos/640/480?random=8367",
      promo: false,
      active: true,
    },
    {
      id: 80,
      name: "Incredible Plastic Mouse",
      description: "Omnis ipsa dolorem fugiat delectus.",
      rating: 2,
      image: "https://picsum.photos/640/480?random=4216",
      promo: false,
      active: true,
    },
    {
      id: 81,
      name: "Generic Soft Shoes",
      description: "Dolor quia natus aspernatur voluptas.",
      rating: 1,
      image: "https://picsum.photos/640/480?random=3432",
      promo: true,
      active: true,
    },
    {
      id: 82,
      name: "Handmade Concrete Sausages",
      description:
        "Minus odio ipsam quo qui inventore omnis qui dolore praesentium.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=5695",
      promo: false,
      active: false,
    },
    {
      id: 83,
      name: "Handmade Wooden Chair",
      description: "Eveniet mollitia sunt sit alias aut voluptas eum ad.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=5689",
      promo: false,
      active: false,
    },
    {
      id: 84,
      name: "Gorgeous Rubber Chair",
      description: "Qui animi sed itaque sint.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=977",
      promo: true,
      active: false,
    },
    {
      id: 85,
      name: "Handcrafted Steel Computer",
      description: "Omnis ut aut.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=3905",
      promo: false,
      active: true,
    },
    {
      id: 86,
      name: "Refined Steel Mouse",
      description: "Id ex corrupti voluptatem.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=95",
      promo: true,
      active: false,
    },
    {
      id: 87,
      name: "Handcrafted Cotton Sausages",
      description: "Inventore praesentium doloremque iure ut labore.",
      rating: 2,
      image: "https://picsum.photos/640/480?random=8136",
      promo: false,
      active: false,
    },
    {
      id: 88,
      name: "Incredible Metal Pants",
      description: "Eos consectetur atque quae voluptas perferendis.",
      rating: 5,
      image: "https://picsum.photos/640/480?random=7970",
      promo: true,
      active: true,
    },
    {
      id: 89,
      name: "Unbranded Soft Hat",
      description: "Molestiae et necessitatibus repellendus aut nihil et.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=814",
      promo: true,
      active: true,
    },
    {
      id: 90,
      name: "Awesome Concrete Pants",
      description: "Nesciunt qui illum optio numquam est rem omnis laborum.",
      rating: 2,
      image: "https://picsum.photos/640/480?random=1694",
      promo: false,
      active: false,
    },
    {
      id: 91,
      name: "Small Plastic Tuna",
      description: "Harum et vel ipsum non quidem doloremque est temporibus.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=2101",
      promo: true,
      active: false,
    },
    {
      id: 92,
      name: "Handmade Granite Chair",
      description: "Reiciendis incidunt numquam incidunt.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=7873",
      promo: true,
      active: false,
    },
    {
      id: 93,
      name: "Unbranded Concrete Hat",
      description: "Pariatur dolorum vel eveniet eos quae voluptas.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=9869",
      promo: true,
      active: false,
    },
    {
      id: 94,
      name: "Tasty Fresh Gloves",
      description:
        "Porro laudantium quod blanditiis error velit incidunt omnis et.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=241",
      promo: true,
      active: false,
    },
    {
      id: 95,
      name: "Practical Cotton Mouse",
      description:
        "Reiciendis voluptas a atque dolore non eligendi et omnis tempore.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=2132",
      promo: false,
      active: false,
    },
    {
      id: 96,
      name: "Generic Fresh Car",
      description:
        "Sint voluptate eos quasi sed explicabo sunt nihil minus et.",
      rating: 3,
      image: "https://picsum.photos/640/480?random=2854",
      promo: true,
      active: true,
    },
    {
      id: 97,
      name: "Ergonomic Wooden Table",
      description: "Illo non praesentium totam est expedita ducimus.",
      rating: 2,
      image: "https://picsum.photos/640/480?random=1509",
      promo: true,
      active: true,
    },
    {
      id: 98,
      name: "Refined Rubber Hat",
      description: "Enim et voluptas.",
      rating: 1,
      image: "https://picsum.photos/640/480?random=8187",
      promo: false,
      active: false,
    },
    {
      id: 99,
      name: "Sleek Frozen Shoes",
      description:
        "Molestiae dolorum repellat corporis fugit in asperiores non et explicabo.",
      rating: 4,
      image: "https://picsum.photos/640/480?random=2810",
      promo: true,
      active: true,
    },
    {
      id: 100,
      name: "Practical Fresh Bike",
      description: "Corporis cum voluptatum distinctio.",
      rating: 2,
      image: "https://picsum.photos/640/480?random=381",
      promo: true,
      active: false,
    },
  ],
};
